Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.56.2"

  config.vbguest.auto_update = false
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
  #config.vbguest.no_remote = true

  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false

  # config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__exclude: ".git/"


  config.vm.provision "shell", path: "provision.sh"
end
